version: 2

jobs:
  deploy-enterprise-release:
    docker:
    - image: grafana/grafana-ci-deploy:1.2.0
    steps:
      - checkout
      - run:
          name: download binaries
          command: 'mkdir enterprise-dist && cd enterprise-dist && wget https://dl.grafana.com/enterprise/release/grafana-enterprise_5.4.3_amd64.deb && wget https://dl.grafana.com/enterprise/release/grafana-enterprise-5.4.3-1.x86_64.rpm'
      - run:
          name: gcp credentials
          command: 'echo ${GCP_GRAFANA_UPLOAD_KEY} > /tmp/gcpkey.json'
      - run:
          name: sign in to gcp
          command: '/opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=/tmp/gcpkey.json'
      - run:
          name: Load GPG private key
          command: './scripts/build/load-signing-key.sh'
      - run:
          name: Update Debian repository
          command: './scripts/build/update_repo/update-deb.sh "enterprise" "$GPG_KEY_PASSWORD" "v5.4.3" "enterprise-dist" "grafana-testing-aptly-db" "grafana-testing-repo"'
      - run:
          name: Update RPM repository
          command: './scripts/build/update_repo/update-rpm.sh "enterprise" "$GPG_KEY_PASSWORD" "v5.4.3" "enterprise-dist" "grafana-testing-repo"'

  deploy-release:
    docker:
      - image: grafana/grafana-ci-deploy:1.2.0
    steps:
      - checkout
      - run:
          name: download binaries
          command: 'mkdir dist && cd dist && wget https://dl.grafana.com/oss/release/grafana_5.4.3_amd64.deb && wget https://dl.grafana.com/oss/release/grafana-5.4.3-1.x86_64.rpm'
      - run:
          name: gcp credentials
          command: 'echo ${GCP_GRAFANA_UPLOAD_KEY} > /tmp/gcpkey.json'
      - run:
          name: sign in to gcp
          command: '/opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=/tmp/gcpkey.json'
      - run:
          name: Load GPG private key
          command: './scripts/build/load-signing-key.sh'
      - run:
          name: Update Debian repository
          command: './scripts/build/update_repo/update-deb.sh "oss" "$GPG_KEY_PASSWORD" "v5.4.3" "dist" "grafana-testing-aptly-db" "grafana-testing-repo"'
      - run:
          name: Update RPM repository
          command: './scripts/build/update_repo/update-rpm.sh "oss" "$GPG_KEY_PASSWORD" "v5.4.3" "dist" "grafana-testing-repo"'

workflows:
  version: 2
  release:
    jobs:
      - deploy-release
      - deploy-enterprise-release
