name: Frontend ESLint

on:
  pull_request:
    paths:
    - '**.ts'
    - '**.tsx'

jobs:
  build:
    name: Run Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install -g yarn
      - run: yarn install --pure-lockfile
      - uses: eslint/github-action@v0
