name: Build Grafana Storybook (test action)

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  build:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install -g yarn now
    - run: yarn install --pure-lockfile
    - name: Verify if storybook should be deployed
      uses: ./.github/actions/verify-deploy-storybook
      id: deployVerify
    - name: Build Storybook
      if: steps.deployVerify.outputs.shouldDeploy == 'true'
      run: yarn storybook:build
