name: Build Grafana Storybook (test action)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install -g yarn
    - run: yarn add -W @actions/core @actions/github
    # - run: yarn storybook:build
    - uses: ./.github/actions/deploy-storybook
