name: Build Grafana Storybook (test action)

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  build:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Building commit ${GITHUB_SHA}
        run: echo ${GITHUB_SHA}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install -g yarn
      - run: yarn install --pure-lockfile
      - name: Build Storybook
        run: yarn storybook:build
      - name: Validate build location
        run: ls ${GITHUB_WORKSPACE}/packages/grafana-ui/dist/storybook
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: grafanalabs-global
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_STORYBOOK_SERVICE_ACCOUNT }}
          CLI: gsutil
        with:
          args: -m cp -r ${GITHUB_WORKSPACE}/packages/grafana-ui/dist/storybook  gs://grafana-storybook/${GITHUB_SHA}
