name: Build Grafana Storybook (test action)

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  build:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    env:
      GIT_HASH: ${git rev-parse --short HEAD}
    steps:
      - name: Setting git short
        uses: srt32/git-actions@v0.0.3
        with:
          args: echo "::set-env name=GIT_HASH:$(git rev-parse --short HEAD)"
      - uses: actions/checkout@v1
      - name: Building commit
        run: echo "Building from commit ${GIT_HASH} on branch ${GITHUB_REF}"
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install -g yarn
      - run: yarn install --pure-lockfile
      - name: Build Storybook
        run: yarn storybook:build
      - name: Validate build location
        run: ls ${GITHUB_WORKSPACE}/packages/grafana-ui/dist/storybook
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: grafanalabs-global
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_STORYBOOK_SERVICE_ACCOUNT }}
          CLI: gsutil
        with:
          args: -m cp -r ${GITHUB_WORKSPACE}/packages/grafana-ui/dist/storybook  gs://grafana-storybook/${GIT_HASH}
      - name: Deploy URL
        run: echo https://storage.googleapis.com/grafana-storybook/${GIT_HASH}/index.html
      
