name: Build Release Storybook

on:
  release:
    types: [created]

jobs:
  build:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.sha}} 
      - name: Get the version
        id: get_version
        run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Building commit
        run: echo "Building from commit ${GIT_HASH} on branch ${GITHUB_REF}" into version ${{VERSION}}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install -g yarn
      - run: yarn install --pure-lockfile
      - name: Build Storybook
        run: yarn storybook:build
      - name: Validate build location
        run: ls ${GITHUB_WORKSPACE}/packages/grafana-ui/dist/storybook
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: grafanalabs-global
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_STORYBOOK_SERVICE_ACCOUNT }}
          CLI: gsutil
        with:
          args: -m cp -r ${GITHUB_WORKSPACE}/packages/grafana-ui/dist/storybook  gs://grafana-storybook/${{VERSION}}
      - name: Deploy URL
        run: echo https://storage.googleapis.com/grafana-storybook/${{VERSION}}/index.html
      
